### ISSUE TITLE
[14.0] maintenance_plan view error on installation 

### ISSUE THREAD

**Issue by llabusch93** [OCA/maintenance#132]
Hello,

if I try to install _maintenance_plan_, I get the following error:
```Tree child can only have one of field, button, control, groupby, widget, header tag (not notebook)

View name: equipment.request.form.inherit
Error context:
 view: ir.ui.view(1596,)
 xmlid: hr_equipment_request_view_form
 view.model: maintenance.request
 view.parent: ir.ui.view(407,)
 file: /home/odoodev/git/maintenance/maintenance_plan/views/maintenance_equipment_views.xml


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/odoodev/git/odoo/odoo/service/server.py", line 1198, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "/home/odoodev/git/odoo/odoo/modules/registry.py", line 89, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/odoodev/git/odoo/odoo/modules/loading.py", line 455, in load_modules
    loaded_modules, update_module, models_to_check)
  File "/home/odoodev/git/odoo/odoo/modules/loading.py", line 348, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/home/odoodev/git/odoo/odoo/modules/loading.py", line 221, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package)
  File "/home/odoodev/git/odoo/odoo/modules/loading.py", line 69, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind)
  File "/home/odoodev/git/odoo/odoo/tools/convert.py", line 733, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate)
  File "/home/odoodev/git/odoo/odoo/tools/convert.py", line 799, in convert_xml_import
    obj.parse(doc.getroot())
  File "/home/odoodev/git/odoo/odoo/tools/convert.py", line 719, in parse
    self._tag_root(de)
  File "/home/odoodev/git/odoo/odoo/tools/convert.py", line 685, in _tag_root
    )) from e
odoo.tools.convert.ParseError: while parsing /home/odoodev/git/maintenance/maintenance_plan/views/maintenance_equipment_views.xml:59, near
<record id="hr_equipment_request_view_form" model="ir.ui.view">
        <field name="name">equipment.request.form.inherit</field>
        <field name="model">maintenance.request</field>
        <field name="inherit_id" ref="maintenance.hr_equipment_request_view_form"/>
        <field name="arch" type="xml">
            <data><field name="maintenance_type" position="after">
                <field name="maintenance_kind_id"/>
            </field>
            <field name="description" position="replace">
                <notebook>
                    <page string="Instructions">
                        <field name="note" placeholder="Describe the maintenance to do..."/>
                    </page>
                    <page string="Notes">
                        <field name="description" placeholder="Internal notes..."/>
                    </page>
                </notebook>
            </field>
        </data></field>
    </record>
```

As it says that the notebook element is not allowed in a tree, the `<field name="description" position="replace">` is not specific enough as there might be two fields _description_ in the same view?

**Comment by etobella** [comment]
Mmmh, can you check if the module hr_maintenance has been auto installed? I think there was a problem with that module.
