### ISSUE TITLE
Maintenance: generate preventive maintenance requests - Class Type Error

### ISSUE THREAD

**Issue by thor-mjolnir-90** [OCA/maintenance#321]
When attempting to run the scheduled action to generate planned maintenance requests this error appears in the Odoo server error box and no planned requests are generated. Can you advise what I can do to fix? 

ValueError: <class 'TypeError'>: "'<=' not supported between instances of 'NoneType' and 'datetime.date'" while evaluating
'model._cron_generate_requests()'

Odoo 12.0-20210920

Error:
Odoo Server Error

Traceback (most recent call last):
  File "F:\Program Files (x86)\Odoo 12.0\server\odoo\tools\safe_eval.py", line 352, in safe_eval
    return unsafe_eval(c, globals_dict, locals_dict)
  File "", line 1, in <module>
  File "f:\program files (x86)\odoo 12.0\server\odoo\addons\maintenance_plan\models\maintenance_equipment.py", line 110, in _cron_generate_requests
    equipment._create_new_request(plan)
  File "f:\program files (x86)\odoo 12.0\server\odoo\addons\maintenance_plan_activity\models\maintenance.py", line 21, in _create_new_request
    new_requests = super()._create_new_request(maintenance_plan)
  File "f:\program files (x86)\odoo 12.0\server\odoo\addons\maintenance_plan\models\maintenance_equipment.py", line 88, in _create_new_request
    while next_maintenance_date <= horizon_date:
TypeError: '<=' not supported between instances of 'NoneType' and 'datetime.date'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Program Files (x86)\Odoo 12.0\server\odoo\http.py", line 656, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "F:\Program Files (x86)\Odoo 12.0\server\odoo\http.py", line 314, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "F:\Program Files (x86)\Odoo 12.0\server\odoo\tools\pycompat.py", line 87, in reraise
    raise value
  File "F:\Program Files (x86)\Odoo 12.0\server\odoo\http.py", line 698, in dispatch
    result = self._call_function(**self.params)
  File "F:\Program Files (x86)\Odoo 12.0\server\odoo\http.py", line 346, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "F:\Program Files (x86)\Odoo 12.0\server\odoo\service\model.py", line 98, in wrapper
    return f(dbname, *args, **kwargs)
  File "F:\Program Files (x86)\Odoo 12.0\server\odoo\http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "F:\Program Files (x86)\Odoo 12.0\server\odoo\http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "F:\Program Files (x86)\Odoo 12.0\server\odoo\http.py", line 519, in response_wrap
    response = f(*args, **kw)
  File "f:\program files (x86)\odoo 12.0\server\odoo\addons\web\controllers\main.py", line 967, in call_button
    action = self._call_kw(model, method, args, {})
  File "f:\program files (x86)\odoo 12.0\server\odoo\addons\web\controllers\main.py", line 955, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "F:\Program Files (x86)\Odoo 12.0\server\odoo\api.py", line 759, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "F:\Program Files (x86)\Odoo 12.0\server\odoo\api.py", line 746, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "f:\program files (x86)\odoo 12.0\server\odoo\addons\base\models\ir_cron.py", line 83, in method_direct_trigger
    self.sudo(user=cron.user_id.id).ir_actions_server_id.run()
  File "f:\program files (x86)\odoo 12.0\server\odoo\addons\base\models\ir_actions.py", line 546, in run
    res = func(action, eval_context=eval_context)
  File "f:\program files (x86)\odoo 12.0\server\odoo\addons\base\models\ir_actions.py", line 437, in run_action_code_multi
    safe_eval(action.sudo().code.strip(), eval_context, mode="exec", nocopy=True)  # nocopy allows to return 'action'
  File "F:\Program Files (x86)\Odoo 12.0\server\odoo\tools\safe_eval.py", line 375, in safe_eval
    pycompat.reraise(ValueError, ValueError('%s: "%s" while evaluating\n%r' % (ustr(type(e)), ustr(e), expr)), exc_info[2])
  File "F:\Program Files (x86)\Odoo 12.0\server\odoo\tools\pycompat.py", line 86, in reraise
    raise value.with_traceback(tb)
  File "F:\Program Files (x86)\Odoo 12.0\server\odoo\tools\safe_eval.py", line 352, in safe_eval
    return unsafe_eval(c, globals_dict, locals_dict)
  File "", line 1, in <module>
  File "f:\program files (x86)\odoo 12.0\server\odoo\addons\maintenance_plan\models\maintenance_equipment.py", line 110, in _cron_generate_requests
    equipment._create_new_request(plan)
  File "f:\program files (x86)\odoo 12.0\server\odoo\addons\maintenance_plan_activity\models\maintenance.py", line 21, in _create_new_request
    new_requests = super()._create_new_request(maintenance_plan)
  File "f:\program files (x86)\odoo 12.0\server\odoo\addons\maintenance_plan\models\maintenance_equipment.py", line 88, in _create_new_request
    while next_maintenance_date <= horizon_date:
ValueError: <class 'TypeError'>: "'<=' not supported between instances of 'NoneType' and 'datetime.date'" while evaluating
'model._cron_generate_requests()'

**Comment by thor-mjolnir-90** [comment]
Resolved, I had some templates setup that needed to be removed and issue resolved.
